// Generated by gencpp from file dim/myservice.msg
// DO NOT EDIT!


#ifndef DIM_MESSAGE_MYSERVICE_H
#define DIM_MESSAGE_MYSERVICE_H

#include <ros/service_traits.h>


#include <dim/myserviceRequest.h>
#include <dim/myserviceResponse.h>


namespace dim
{

struct myservice
{

typedef myserviceRequest Request;
typedef myserviceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct myservice
} // namespace dim


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dim::myservice > {
  static const char* value()
  {
    return "fd72814fc41c6bccdf8759d8dea09f77";
  }

  static const char* value(const ::dim::myservice&) { return value(); }
};

template<>
struct DataType< ::dim::myservice > {
  static const char* value()
  {
    return "dim/myservice";
  }

  static const char* value(const ::dim::myservice&) { return value(); }
};


// service_traits::MD5Sum< ::dim::myserviceRequest> should match 
// service_traits::MD5Sum< ::dim::myservice > 
template<>
struct MD5Sum< ::dim::myserviceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dim::myservice >::value();
  }
  static const char* value(const ::dim::myserviceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dim::myserviceRequest> should match 
// service_traits::DataType< ::dim::myservice > 
template<>
struct DataType< ::dim::myserviceRequest>
{
  static const char* value()
  {
    return DataType< ::dim::myservice >::value();
  }
  static const char* value(const ::dim::myserviceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dim::myserviceResponse> should match 
// service_traits::MD5Sum< ::dim::myservice > 
template<>
struct MD5Sum< ::dim::myserviceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dim::myservice >::value();
  }
  static const char* value(const ::dim::myserviceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dim::myserviceResponse> should match 
// service_traits::DataType< ::dim::myservice > 
template<>
struct DataType< ::dim::myserviceResponse>
{
  static const char* value()
  {
    return DataType< ::dim::myservice >::value();
  }
  static const char* value(const ::dim::myserviceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DIM_MESSAGE_MYSERVICE_H
