// Generated by gencpp from file service_tut/myservice.msg
// DO NOT EDIT!


#ifndef SERVICE_TUT_MESSAGE_MYSERVICE_H
#define SERVICE_TUT_MESSAGE_MYSERVICE_H

#include <ros/service_traits.h>


#include <service_tut/myserviceRequest.h>
#include <service_tut/myserviceResponse.h>


namespace service_tut
{

struct myservice
{

typedef myserviceRequest Request;
typedef myserviceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct myservice
} // namespace service_tut


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::service_tut::myservice > {
  static const char* value()
  {
    return "fd72814fc41c6bccdf8759d8dea09f77";
  }

  static const char* value(const ::service_tut::myservice&) { return value(); }
};

template<>
struct DataType< ::service_tut::myservice > {
  static const char* value()
  {
    return "service_tut/myservice";
  }

  static const char* value(const ::service_tut::myservice&) { return value(); }
};


// service_traits::MD5Sum< ::service_tut::myserviceRequest> should match 
// service_traits::MD5Sum< ::service_tut::myservice > 
template<>
struct MD5Sum< ::service_tut::myserviceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::service_tut::myservice >::value();
  }
  static const char* value(const ::service_tut::myserviceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::service_tut::myserviceRequest> should match 
// service_traits::DataType< ::service_tut::myservice > 
template<>
struct DataType< ::service_tut::myserviceRequest>
{
  static const char* value()
  {
    return DataType< ::service_tut::myservice >::value();
  }
  static const char* value(const ::service_tut::myserviceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::service_tut::myserviceResponse> should match 
// service_traits::MD5Sum< ::service_tut::myservice > 
template<>
struct MD5Sum< ::service_tut::myserviceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::service_tut::myservice >::value();
  }
  static const char* value(const ::service_tut::myserviceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::service_tut::myserviceResponse> should match 
// service_traits::DataType< ::service_tut::myservice > 
template<>
struct DataType< ::service_tut::myserviceResponse>
{
  static const char* value()
  {
    return DataType< ::service_tut::myservice >::value();
  }
  static const char* value(const ::service_tut::myserviceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVICE_TUT_MESSAGE_MYSERVICE_H
